development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: nh_qis
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: nh_qis_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
